#!/bin/bash

LOCAL_SSH_AUTH_SOCK="$HOME/.ssh/$HOSTNAME.ssh_auth_sock"

if test "$SSH_AUTH_SOCK"; then
    ln -sf $SSH_AUTH_SOCK "$LOCAL_SSH_AUTH_SOCK"
fi

# Start xauth when doing X forwarding
# http://serverfault.com/questions/278743/ssh-x11-not-working
if read proto cookie && [ -n "$DISPLAY" ]; then
    if [ `echo $DISPLAY | cut -c1-10` = 'localhost:' ]; then
        # X11UseLocalhost=yes
        echo add unix:`echo $DISPLAY | cut -c11-` $proto $cookie
    else
        # X11UseLocalhost=no
        echo add $DISPLAY $proto $cookie
    fi | xauth -q -
fi
