alias dc='docker-compose'
alias dcr='docker-compose run --rm'
alias dcu='docker-compose up'
alias dr='docker run -it --rm'
alias drv='docker run -it --rm -v $PWD:/usr/src/app:delegated -w /usr/src/app'

alias gti=git
alias gap='git add --patch'
alias gau='git add --update'
alias gciane='git commit --amend --no-edit'
alias gd='git diff'
alias gdc='git diff --cached'
alias glns='git log --name-status'
alias glp='git log --patch'
alias grc='git rebase --continue'
alias gri='git rebase --interactive'
